# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12cf646d2c0a0bd24b85f0c62720d9e724259c343555f36e5ae12b9bff3a5c075f662a1662a2a4313f15844cff691362bd54be72dd26423b288f356e21df33f2

test:
  secret_key_base: 9ba5bc9cf2fbf6210a127157ef6236b198a8678ff11686f4e5400f69c8e7803e94e1ce99b41ec00c63f057a40dcbf6d21798b4835619f6f875567198a27d596b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
